=== rjmoggach/python-dirtt/dirtt/data/dirtt.dtd
<!--

  XML Document Type Definition for python-dirtt - Directory Tree Templater.

  Copyright (C) 2012 Dashing Collective Inc.

  This is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

  This document is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

-->

<!--
  dirtt is an XML language - Typical usage:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirtt PUBLIC "-//DSHNG//DTD dirtt 0.1.9b1//EN"
      "http://opensource.dashing.tv/dtds/dirtt.dtd">
<dirtt>
</dirtt>
-->

<!-- 'root' of directory tree template, our starting point -->
<!ELEMENT   dirtt       (dir | file | link )*>
<!ATTLIST   dirtt
            basename    CDATA        #REQUIRED
            name        CDATA        #REQUIRED
            version     CDATA        #REQUIRED
            dirname     CDATA        #REQUIRED>

<!-- Folder/Directory -->
<!ELEMENT   dir         (dir | file | link )*>
<!ATTLIST   dir
            basename    CDATA        #REQUIRED
            id          ID           #IMPLIED
            name        CDATA        #IMPLIED
            username    CDATA        #IMPLIED
            group       CDATA        #IMPLIED
            perms       CDATA        #IMPLIED
            dirname     CDATA        #IMPLIED>

<!-- File -->
<!ELEMENT   file        EMPTY>
<!ATTLIST   file
            basename    CDATA        #REQUIRED
            id          ID           #IMPLIED
            name        CDATA        #IMPLIED
            username    CDATA        #IMPLIED
            group       CDATA        #IMPLIED
            perms       CDATA        #IMPLIED
            href        CDATA        #IMPLIED
            dirname     CDATA        #IMPLIED>

<!-- Symbolic Link -->
<!ELEMENT  link         EMPTY>
<!ATTLIST  link
           basename     CDATA        #REQUIRED
           id           ID           #IMPLIED
           name         CDATA        #IMPLIED
           idref        IDREF        #IMPLIED
           ref          CDATA        #IMPLIED
           dirname      CDATA        #IMPLIED>

=== rjmoggach/python-dirtt/dirtt/data/templates/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirtt PUBLIC "-//DSHNG//DTD dirtt 0.1.4//EN" "http://opensource.dashing.tv/dtds/dirtt.dtd">
<dirtt name="Project Tree" version="0.1.9b6" dirname="{{project_root}}" basename="{{project_path}}" username="pipeline" group="artist" perms="02755" xmlns:xi="http://www.w3.org/2001/XInclude">
<!-- M A S T E R   F O L D E R -->
  <dir name="Project Master Directory" basename="master" username="pipeline" group="supervisor" perms="02755" xmlns:xi="http://www.w3.org/2001/XInclude">
  <xi:include href="project_master.xml" parse="xml"/>
  </dir>
<!-- W O R K   F O L D E R -->
  <dir name="Project Work Directory" basename="work" username="pipeline" group="supervisor" perms="02755">
  </dir>
<!-- S E Q U E N C E S   F O L D E R -->
  <dir name="Project Sequences Directory" basename="sequences" username="pipeline" group="supervisor" perms="02755">
  </dir>
<!-- I N C O M I N G   F O L D E R -->
  <dir name="Project Incoming Directory" basename="sequences" username="pipeline" group="artist" perms="02777">
  </dir>
<!-- P R O D U C T I O N   F O L D E R -->
  <dir name="Project Production Directory" basename="production" username="pipeline" group="supervisor" perms="02775">
  </dir>
<!-- F L A M E   F O L D E R -->
  <dir name="Project Flame Directory" basename="flame" username="pipeline" group="supervisor" perms="02777">
  </dir>
</dirtt>

=== rjmoggach/python-dirtt/dirtt/data/templates/project_production.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirtt PUBLIC "-//DSHNG//DTD dirtt 0.1.4//EN" "http://opensource.dashing.tv/dtds/dirtt.dtd">
<dirtt name="Production Tree" version="0.1.9b1" dirname="{{project_root}}/{{project_path}}" basename="production" username="pipeline" group="production" perms="02775">
  <!-- E D I T S   F O L D E R -->
  <dir basename="edits" username="pipeline" group="production" perms="02777">
    <dir basename="_yyyy_mm_dd_template" username="pipeline" group="artist" perms="02777">
      <dir basename="edl" username="pipeline" group="artist" perms="02775"/>
      <dir basename="movies" username="pipeline" group="artist" perms="02775"/>
      <dir basename="images" username="pipeline" group="artist" perms="02775"/>
    </dir>
  </dir>
  <!-- P O S T I N G S   F O L D E R -->
  <dir basename="postings" username="pipeline" group="production" perms="02777">
    <dir basename="_yyyy_mm_dd_template" username="pipeline" group="artist" perms="02777">
      <dir basename="other" username="pipeline" group="artist" perms="02775"/>
      <dir basename="movies" username="pipeline" group="artist" perms="02775"/>
      <dir basename="images" username="pipeline" group="artist" perms="02775"/>
    </dir>
  </dir>
  <!-- C R E A T I V E   F O L D E R -->
  <dir basename="creative" username="pipeline" group="production" perms="02777">
    <dir basename="animatic" username="pipeline" group="artist" perms="02775"/>
    <dir basename="storyboard" username="pipeline" group="artist" perms="02775"/>
    <dir basename="script" username="pipeline" group="artist" perms="02775"/>
    <dir basename="breakdown" username="pipeline" group="artist" perms="02775"/>
    <dir basename="treatment" username="pipeline" group="artist" perms="02775"/>
    <dir basename="reference" username="pipeline" group="artist" perms="02775">
      <dir basename="client" username="pipeline" group="production" perms="02775"/>
      <dir basename="development" username="pipeline" group="artist" perms="02777"/>
    </dir>
  </dir>
  <!-- F I N A N C I A L   F O L D E R -->
  <dir basename="business" username="pipeline" group="production" perms="02770">
    <dir basename="bid" username="pipeline" group="production" perms="02770"/>
    <dir basename="legal" username="pipeline" group="production" perms="02770">
      <dir basename="contracts" username="pipeline" group="production" perms="02770"/>
      <dir basename="nda" username="pipeline" group="production" perms="02770"/>
    </dir>
    <dir basename="invoices" username="pipeline" group="production" perms="02770"/>
    <dir basename="purchases" username="pipeline" group="production" perms="02770"/>
    <dir basename="budget" username="pipeline" group="production" perms="02770"/>
  </dir>
  <!-- G R A P H I C S   F O L D E R -->
  <dir basename="graphics" username="pipeline" group="artist" perms="02775">
    <dir basename="logos" username="pipeline" group="artist" perms="02775"/>
    <dir basename="endtags" username="pipeline" group="artist" perms="02775"/>
    <dir basename="legals" username="pipeline" group="artist" perms="02775"/>
    <link basename="fonts" ref="../../master/data/fonts"/>
  </dir>
  <!-- A U D I O   F O L D E R -->
  <dir basename="audio" username="pipeline" group="artist" perms="02775"/>
  <!-- S L A T E S   F O L D E R -->
  <dir basename="slates" username="pipeline" group="production" perms="02777"/>
  <!-- N O T E S   F O L D E R -->
  <dir basename="notes" username="pipeline" group="production" perms="02775"/>
  <!-- S H O T S H E E T S   F O L D E R -->
  <dir basename="shotsheets" username="pipeline" group="production" perms="02775">
    <dir basename="frames" username="pipeline" group="artist" perms="02775"/>
  </dir>
  <!-- S C H E D U L E   F O L D E R -->
  <dir basename="schedule" username="pipeline" group="production" perms="02775"/>
</dirtt>

=== rjmoggach/python-dirtt/dirtt/data/templates/project_shot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirtt PUBLIC "-//DSHNG//DTD dirtt 0.1.4//EN" "http://opensource.dashing.tv/dtds/dirtt.dtd">
<dirtt name="Shot Tree" version="0.1.9b6" dirname="{{project_root}}/{{project_path}}/sequences/{{sequence_name}}" basename="{{shot_name}}" username="pipeline" group="supervisor" perms="02775">
<!-- I M A G E S   F O L D E R -->
	<dir name="Shot Images Folder" basename="images" username="pipeline" group="supervisor" perms="02755">
	  <link basename="master" ref="../../../../master/images"/>
		<dir basename="cg" username="pipeline" group="artist" perms="02775">
		</dir>
		<dir basename="comp" username="pipeline" group="artist" perms="02775"/>
		<dir basename="design" username="pipeline" group="artist" perms="02775"/>
		<dir basename="paint" username="pipeline" group="artist" perms="02775"/>
		<dir basename="roto" username="pipeline" group="artist" perms="02775"/>
		<dir basename="plates" username="pipeline" group="artist" perms="02775"/>
		<dir basename="reference" username="pipeline" group="artist" perms="02775"/>
		<dir basename="textures" username="pipeline" group="artist" perms="02775">
	    <link basename="master" ref="../../../../master/images/textures"/>
  		<dir basename="3dPaintTextures" username="pipeline" group="artist" perms="02775"/>
		</dir>
		<dir basename="volumetrics" username="pipeline" group="artist" perms="02755">
		  <dir basename="bty" username="pipeline" group="artist" perms="02775" />
		  <dir basename="zt" username="pipeline" group="artist" perms="02775" />
		  <dir basename="env" username="pipeline" group="artist" perms="02775" />
		</dir>
	</dir>
  <!-- M E D I A    F O L D E R -->
	<dir name="Shot Media Folder" basename="media" username="pipeline" group="supervisor" perms="02775">
		<dir basename="audio" username="pipeline" group="artist" perms="02775"/>
		<dir basename="movies" username="pipeline" group="artist" perms="02775"/>
		<dir basename="edits" username="pipeline" group="artist" perms="02775"/>
	</dir>
	<!-- D A T A   F O L D E R -->
	<dir name="Shot Data Folder" basename="data" username="pipeline" group="artist" perms="02775">
    <link basename="master" ref="../../../../master/data"/>
		<dir basename="cache" username="pipeline" group="artist" perms="02775">
			<dir basename="fluid" username="pipeline" group="artist" perms="02775"/>
			<dir basename="houdini" username="pipeline" group="artist" perms="02775"/>
			<dir basename="volumetrics" username="pipeline" group="artist" perms="02775"/>
		</dir>
		<dir basename="renderData" username="pipeline" group="artist" perms="02775">
		  <dir basename="depth" username="pipeline" group="artist" perms="02775"/>
		  <dir basename="fur" username="pipeline" group="artist" perms="02775">
		    <dir basename="furFiles" username="pipeline" group="artist" perms="02775"/>
		    <dir basename="furShadowMap" username="pipeline" group="artist" perms="02775"/>
		    <dir basename="furAttrMap" username="pipeline" group="artist" perms="02775"/>
		    <dir basename="furImages" username="pipeline" group="artist" perms="02775"/>
		    <dir basename="furEqualMap" username="pipeline" group="artist" perms="02775"/>
	    </dir>
		  <dir basename="mentalRay" username="pipeline" group="artist" perms="02775"/>
		  <dir basename="iprImages" username="pipeline" group="artist" perms="02775"/>
		  <dir basename="shaders" username="pipeline" group="artist" perms="02775"/>
		</dir>
		<dir basename="particles" username="pipeline" group="artist" perms="02775"/>
		<dir basename="camera" username="pipeline" group="artist" perms="02775"/>
		<dir basename="chan" username="pipeline" group="artist" perms="02775"/>
		<dir basename="geo" username="pipeline" group="artist" perms="02775"/>
		<dir basename="lut" username="pipeline" group="artist" perms="02775"/>
		<dir basename="mocap" username="pipeline" group="artist" perms="02775"/>
		<dir basename="moco" username="pipeline" group="artist" perms="02775"/>
		<dir basename="timewarp" username="pipeline" group="artist" perms="02775"/>
		<dir basename="volumetrics" username="pipeline" group="artist" perms="02755">
		  <dir basename="particles" username="pipeline" group="artist" perms="02775" />
		  <dir basename="cache" username="pipeline" group="artist" perms="02775" />
		</dir>
	</dir>
  <!-- T O O L S   F O L D E R -->
  <dir basename="tools" username="pipeline" group="supervisor" perms="02775">
    <dir basename="maya" username="pipeline" group="supervisor" perms="02775">
      <dir basename="mel" username="pipeline" group="artist" perms="02775"/>
      <dir basename="python" username="pipeline" group="artist" perms="02775"/>
      <dir basename="shelves" username="pipeline" group="artist" perms="02775"/>
      <dir basename="modules" username="pipeline" group="artist" perms="02775"/>
      <dir basename="templates" username="pipeline" group="artist" perms="02775"/>
    </dir>
	  <dir basename="houdini" username="pipeline" group="artist" perms="02775">
		<dir basename ="dso" username="pipeline" group="artist" perms="02775"/>
    <dir basename ="otls" username="pipeline" group="artist" perms="02775"/>
    <dir basename ="scripts" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <dir basename="nuke" username="pipeline" group="artist" perms="02775">
      <dir basename="gizmos" username="pipeline" group="artist" perms="02775"/>
      <dir basename="plugins" username="pipeline" group="artist" perms="02775"/>
      <dir basename="shelves" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <dir basename="scripts" username="pipeline" group="artist" perms="02775"/>
    <dir basename="vray" username="pipeline" group="artist" perms="02775"/>
  </dir>
<!-- S C E N E S   F O L D E R -->
  <dir name="Shot Scenes Folder" basename="scenes" username="pipeline" group="artist" perms="02775">
    <link basename="master" ref="../../../../master/"/>
    <dir basename="tracking" username="pipeline" group="artist" perms="02775"/>
    <dir basename="anim" username="pipeline" group="artist" perms="02775"/>
    <dir basename="light" username="pipeline" group="artist" perms="02775"/>
  </dir>
  <dir basename=".autosave" username="pipeline" group="artist" perms="02777"/>
<!-- V O L U M E T R I C S   F O L D E R -->
  <dir name="Shot Volumetrics Folder" basename="scenes" username="pipeline" group="artist" perms="02755">
    <link basename="particles" ref="../data/volumetrics/particles/"/>
    <link basename="cache" ref="../data/volumetrics/cache/"/>
    <link basename="render" ref="../images/volumetrics/"/>
    <dir basename="options" username="pipeline" group="artist" perms="02775"/>
    <dir basename="scenes" username="pipeline" group="artist" perms="02775"/>
  </dir>
	<file basename="workspace.mel" username="pipeline" group="supervisor" perms="02775" href="workspace.mel"/>
<!-- C O M P   F O L D E R -->
  <dir name="Shot Comp Folder" basename="comp" username="pipeline" group="supervisor" perms="02755">
    <dir basename="nuke" username="pipeline" group="artist" perms="02775"/>
    <dir basename="roto" username="pipeline" group="artist" perms="02775"/>
  </dir>
  <!-- P A I N T   F O L D E R -->
  <link basename="paint" ref="./images/paint"/>
  <!-- D E S I G N   F O L D E R -->
  <link basename="design" ref="./images/design"/>
</dirtt>

=== rjmoggach/python-dirtt/dirtt/data/templates/project_master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirtt PUBLIC "-//STUDIO//DTD dirtt 0.2.0rc3//EN" "http://robmoggach.github.io/python-dirtt/dtds/dirtt.dtd">
<dirtt name="Master Tree" version="0.2.0rc3" dirname="{{project_root}}/{{project_path}}" basename="master" username="pipeline" group="supervisor" perms="02775">
    <!-- R I G   F O L D E R -->
    <dir basename="rig" username="pipeline" group="supervisor" perms="02755">
      <dir basename="cam" username="pipeline" group="artist" perms="02775"/>
      <dir basename="char" username="pipeline" group="artist" perms="02775"/>
      <dir basename="env" username="pipeline" group="artist" perms="02775"/>
      <dir basename="prop" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <!-- S U R V E Y   F O L D E R -->
    <dir basename="survey" username="pipeline" group="supervisor" perms="02755">
      <dir basename="cam" username="pipeline" group="artist" perms="02775"/>
      <dir basename="char" username="pipeline" group="artist" perms="02775"/>
      <dir basename="env" username="pipeline" group="artist" perms="02775"/>
      <dir basename="prop" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <!-- M O D E L   F O L D E R -->
    <dir basename="model" username="pipeline" group="supervisor" perms="02755">
      <dir basename="char" username="pipeline" group="artist" perms="02775"/>
      <dir basename="env" username="pipeline" group="artist" perms="02775"/>
      <dir basename="prop" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <!-- F X   F O L D E R -->
    <dir basename="fx" username="pipeline" group="supervisor" perms="02755">
      <dir basename="char" username="pipeline" group="artist" perms="02775"/>
      <dir basename="env" username="pipeline" group="artist" perms="02775"/>
      <dir basename="prop" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <!-- L I G H T   F O L D E R -->
    <dir basename="light" username="pipeline" group="supervisor" perms="02755">
      <dir basename="char" username="pipeline" group="artist" perms="02775"/>
      <dir basename="env" username="pipeline" group="artist" perms="02775"/>
      <dir basename="prop" username="pipeline" group="artist" perms="02775"/>
      <link basename="sourceimages" ref="../images/textures"/>
    </dir>
    <!-- C O M P   F O L D E R -->
    <dir basename="comp" username="pipeline" group="supervisor" perms="02755">
      <link basename="lut" ref="../data/lut"/>
      <link basename="lens" ref="../data/lens"/>
      <link basename="chan" ref="../data/chan"/>
      <link basename="timewarp" ref="../data/chan"/>
      <link basename="grain" ref="../images/grain"/>
      <link basename="paint" ref="../images/paint"/>
      <link basename="design" ref="../images/design"/>
      <link basename="fonts" ref="../data/fonts"/>
      <dir basename="scripts" username="pipeline" group="artist" perms="02775"/>
      <dir basename="tools" username="pipeline" group="supervisor" perms="02775">
        <link basename="nuke" ref="../../tools/nuke"/>
      </dir>
    </dir>
    <!-- I M A G E S   F O L D E R -->
    <dir basename="images" username="pipeline" group="supervisor" perms="02755">
      <dir basename="grain" username="pipeline" group="artist" perms="02775"/>
      <dir basename="textures" username="pipeline" group="supervisor" perms="02775">
        <dir basename="cam" username="pipeline" group="artist" perms="02775"/>
        <dir basename="char" username="pipeline" group="artist" perms="02775"/>
        <dir basename="env" username="pipeline" group="artist" perms="02775"/>
        <dir basename="prop" username="pipeline" group="artist" perms="02775"/>
      </dir>
      <dir basename="hdri" username="pipeline" group="artist" perms="02775"/>
      <dir basename="design" username="pipeline" group="artist" perms="02775"/>
      <dir basename="paint" username="pipeline" group="artist" perms="02775">
        <dir basename="ai" username="pipeline" group="artist" perms="02775"/>
        <dir basename="geo" username="pipeline" group="artist" perms="02775"/>
        <dir basename="mudbox" username="pipeline" group="artist" perms="02775"/>
        <dir basename="psd" username="pipeline" group="artist" perms="02775"/>
      </dir>
    </dir>
    <!-- D A T A   F O L D E R -->
    <dir basename="data" username="pipeline" group="supervisor" perms="02755">
      <dir basename="audio" username="pipeline" group="artist" perms="02775"/>
      <dir basename="fonts" username="pipeline" group="artist" perms="02775"/>
      <dir basename="chan" username="pipeline" group="artist" perms="02775"/>
      <dir basename="lens" username="pipeline" group="supervisor" perms="02775">
        <dir basename="uv" username="pipeline" group="artist" perms="02775"/>
        <dir basename="grids" username="pipeline" group="artist" perms="02775"/>
      </dir>
      <dir basename="lut" username="pipeline" group="supervisor" perms="02775"/>
      <dir basename="timewarp" username="pipeline" group="artist" perms="02775"/>
      <dir basename="cache" username="pipeline" group="artist" perms="02775"/>
    </dir>
    <!-- T O O L S   F O L D E R -->
    <dir basename="tools" username="pipeline" group="supervisor" perms="02755">
      <dir basename="config" username="pipeline" group="artist" perms="02775"/>
      <dir basename="environment" username="pipeline" group="artist" perms="02775"/>
      <dir basename="maya" username="pipeline" group="supervisor" perms="02755">
        <dir basename="mel" username="pipeline" group="artist" perms="02775"/>
        <dir basename="python" username="pipeline" group="artist" perms="02775"/>
        <dir basename="presets" username="pipeline" group="artist" perms="02775"/>
        <dir basename="shelves" username="pipeline" group="artist" perms="02775"/>
        <dir basename="templates" username="pipeline" group="artist" perms="02775"/>
      </dir>
      <dir basename="nuke" username="pipeline" group="supervisor" perms="02755">
        <dir basename="plugins" username="pipeline" group="artist" perms="02775"/>
        <dir basename="gizmos" username="pipeline" group="artist" perms="02775"/>
        <dir basename="scripts" username="pipeline" group="artist" perms="02775"/>
      </dir>
      <dir basename="scripts" username="pipeline" group="artist" perms="02775"/>
      <dir basename="vray" username="pipeline" group="artist" perms="02775"/>
    </dir>
</dirtt>

=== rjmoggach/python-dirtt/dirtt/data/dshng/symlinks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirtt PUBLIC "-//DSHNG//DTD dirtt 0.1.4//EN" "/dashing/tools/var/dirtt/dtds/dirtt.dtd">
<dirtt name="Project Tree" version="0.1.4" dirname="{{projects_root}}" basename="{{project_path}}" username="pipeline" group="artist" perms="02755">

<!-- C O N F I G   F O L D E R -->
	<dir name="Project Config Folder" basename="etc" username="pipeline" group="supervisor" perms="02755" id="config-id">
		<dir basename="houdini" username="pipeline" group="supervisor" perms="02755">
			<dir basename="dso" username="pipeline" group="supervisor" perms="02775"/>
            <dir basename="otls" username="pipeline" group="supervisor" perms="02775"/>
            <dir basename="scripts" username="pipeline" group="supervisor" perms="02775"/>
        </dir><!-- houdini -->
		<dir basename="maya" username="pipeline" group="supervisor" perms="02755">
            <dir basename="modules" username="pipeline" group="supervisor" perms="02775"/>
            <dir basename="plugins" username="pipeline" group="supervisor" perms="02775"/>
            <dir basename="scripts" username="pipeline" group="supervisor" perms="02755">
                <dir basename="mel" username="pipeline" group="supervisor" perms="02775"/>
                <dir basename="py" username="pipeline" group="supervisor" perms="02775"/>
            </dir>
			<dir basename="shelves" username="pipeline" group="supervisor" perms="02775"/>
		</dir><!-- maya -->
		<dir basename="nuke" username="pipeline" group="supervisor" perms="02755">
			<dir basename="gizmos" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="menu" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="scripts" username="pipeline" group="supervisor" perms="02775"/>
		</dir><!-- nuke -->
		<dir basename="user" username="pipeline" group="supervisor" perms="02775"/>
		<dir basename="vray" username="pipeline" group="supervisor" perms="02775"/>
	</dir><!-- etc -->

<!-- F L A M E   F O L D E R -->
	<dir name="Project Flame Projects Folder" basename="flame" username="flame" group="supervisor" perms="02775">
	</dir><!-- flame -->

<!-- L I B R A R Y   F O L D E R -->
	<dir name= "Project Library Folder" basename="library" username="pipeline" group="supervisor" perms="02755">
		<dir basename="audio" username="pipeline" group="artist" perms="02775"/>
		<dir basename="data" username="pipeline" group="artist" perms="02755">
			<dir basename="chan" username="pipeline" group="artist" perms="02775"/>
			<dir basename="db" username="pipeline" group="artist" perms="02775"/>
			<dir basename="lut" username="pipeline" group="artist" perms="02775"/>
			<dir basename="mocap" username="pipeline" group="artist" perms="02775"/>
			<dir basename="moco" username="pipeline" group="artist" perms="02775"/>
		</dir><!-- data -->
		<dir basename="img">
			<dir basename="calibration" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="elements" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="grain" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="hdri" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="lens" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="paint" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="textures" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="stock" username="pipeline" group="supervisor" perms="02775"/>
		</dir><!-- img -->
		<dir basename="edits" username="pipeline" group="supervisor" perms="02755">
			<dir basename="_YYYY_MM_DD_name" username="pipeline" group="artist" perms="02755">
				<dir basename="edl" username="pipeline" group="artist" perms="02775"/>
				<dir basename="media" username="pipeline" group="artist" perms="02775"/>
			</dir>
		</dir><!-- edits -->
		<dir basename="fonts" username="pipeline" group="supervisor" perms="02775"/>
		<dir basename="graphics" username="pipeline" group="supervisor" perms="02775"/>
		<dir basename="models" username="pipeline" group="supervisor" perms="02775"/>
		<dir basename="reference" username="pipeline" group="supervisor" perms="02755">
			<dir basename="misc" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="on_set" username="pipeline" group="supervisor" perms="02755">
				<dir basename="_YYYY_MM_DD_name" username="pipeline" group="supervisor" perms="02775">
					<dir basename="edl" username="pipeline" group="supervisor" perms="02775"/>
					<dir basename="media" username="pipeline" group="supervisor" perms="02775"/>
				</dir>
			</dir><!-- on_set -->
		</dir><!-- reference -->
		<dir basename="shaders" username="pipeline" group="supervisor" perms="02755">
			<dir basename="vray" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="rman" username="pipeline" group="supervisor" perms="02775"/>
			<dir basename="mray" username="pipeline" group="supervisor" perms="02775"/>
		</dir><!-- shaders -->
		<dir basename="tools" username="pipeline" group="supervisor" perms="02775"/>
	</dir><!-- library -->

<!-- P R O D U C T I O N   F O L D E R -->
	<dir basename="production" username="pipeline" group="production" perms="02755">
		<dir basename="financial" username="pipeline" group="production" perms="02750">
			<dir basename="bid" username="pipeline" group="production" perms="02770"/>
			<dir basename="invoices" username="pipeline" group="production" perms="02770"/>
			<dir basename="purchases" username="pipeline" group="production" perms="02770"/>
		</dir><!-- financial -->
		<dir basename="creative" username="pipeline" group="production" perms="02755">
			<dir basename="breakdown" username="pipeline" group="production" perms="02775"/>
			<dir basename="script" username="pipeline" group="production" perms="02775"/>
			<dir basename="storyboard" username="pipeline" group="production" perms="02775"/>
			<dir basename="treatment" username="pipeline" group="production" perms="02775"/>
			<dir basename="reference" username="pipeline" group="production" perms="02775"/>
		</dir><!-- creative -->
		<dir basename="notes" username="pipeline" group="production" perms="02775"/>
		<dir basename="postings" username="pipeline" group="production" perms="02755">
			<dir basename="data" username="pipeline" group="production" perms="02775"/>
			<dir basename="stills" username="pipeline" group="production" perms="02775"/>
			<dir basename="movies" username="pipeline" group="production" perms="02775"/>
		</dir><!-- postings -->
		<dir basename="schedule" username="pipeline" group="production" perms="02775"/>
		<dir basename="shotsheets" username="pipeline" group="production" perms="02775"/>

		<link name="config" idref="config-id"/>
		<link name="assets" idref="assets-id"/>
		<link name="top"  idref="root-dir"/>
		<link name="external" ref="/tmp"/>
		<!-- Symbolic links to assets and configuration folders. -->
	</dir><!-- production -->

<!-- S E Q U E N C E S   F O L D E R -->
	<dir basename="sequences" username="pipeline" group="artist" perms="02755">
	</dir><!-- sequences -->

<!-- S H O T S   F O L D E R -->
	<dir basename="shots" username="pipeline" group="artist" perms="02755">
	</dir><!-- shots -->
		
</dirtt>
